--- 
$schemaver: 1.1
name: Test-Repo
type: Command-line App
aliases:
short_description: Test-Repo for meta Data
assignment_group: gro:AV-Clerks
notes: 
maintained_by:
  - brettbeatty
  - ndpete
developed_by_byu: True
ddd:
  business_domain: 
  ubiquitous_language_url: 
  context_map_url: 
links:
  system_documentation_url: google.com
  source_repo_url: https://github.com/test-ndpete-org/Test-Repo
  swagger_urls:
microservice: False
technologies_used:
stages:
  stage:
    urls:
      product_page: github.com
      physical_url: 
      virtual_url: github.com
    hosting_location: Other
    aws_account: 
    relationships: 
      depends_on:
        db_read_write:
        db_read_only:
        software:
      supports:
        software:
          - Shibboleth:production
        service:
          - Phones
      reverse_proxy: 
      runs_on:
        server_cluster:
        virtual_server:
        rack_server:
        blade_server:
tags:
  data-sensitivity: internal
  env: stage
  app: Test-Repo
  team: AD-HR, University Financials, and CRM
federation_json_url: https://raw.githubusercontent.com/test-ndpete-org/Test-Repo/master/.repo-meta.yml
x-anything:

